### ISSUE TITLE
关于新的爬串方式

### ISSUE THREAD

**Issue by Ovler-Young** [Nyaasu66/adnmb_down#5]
可以参考 https://github.com/ColdThunder11/AdnmbBackup-gui ， 使用 https://nmb.fastmirror.org/Api/thread?id={{thread}}&page={{page}} ，可以直接爬取前99页；再往后的需要登录账号，通过cookie验证。
具体api在这里 https://gist.github.com/anonymous/53b7f88052dd65efb0c21310ccd2a718
应该也可以参考 https://github.com/Mfweb/wechatadao 这个项目的api

**Comment by Mr-Ao-Dragon** [comment]
a岛没了，不用爬了
